### ISSUE TITLE
ReStructure the repo

### ISSUE THREAD

**Issue by bilal-23** [bilal-23/HacktoberFest2021-Python#57]
Move all files into a particular folder.
Calculator.py file should be moved into a new folder named Calcualtor.
For Algorithms like 8Queens_Genetic_Algorithm.py and BFS, create a folder named Algorithms and move the files in their

**Comment by Ramprashanth1** [comment]
can you assign this to me

**Comment by bilal-23** [comment]
@Mihaylov93 Hey can you please raise the PR again, actually it was closed by one of the collaborators.

**Comment by bilal-23** [comment]
@Ramprashanth1  Sure, there are still many projects which are not sorted accordingly.

**Comment by Ramprashanth1** [comment]
I have made a pull request. Thanks for assigning me this.

**Comment by bilal-23** [comment]
@Ramprashanth1 Good work mate,

**Comment by Ramprashanth1** [comment]
Thanks
